language: python
python:
  - "3.6"
# command to install dependencies
cache: pip3
install:
  - 'pip install -r requirements.txt'
# command to run tests
script:
  - python -m unittest discover tests
os: "linux"
dist: "trusty"
notifications:
    on_success: never
    on_failure: never